services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./minio:/data
    command: server /data --console-address ":9001"
    networks:
      - service_network
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.33.0
    container_name: weaviated
    ports:
      - 8080:8080
      - 50051:50051 # grpc_port
    volumes:
    - ./weaviate:/var/lib/weaviate
    environment:
      DISABLE_TELEMETRY: 'true'
      QUERY_DEFAULTS_LIMIT: 25
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'user-a-key,user-b-key'
      AUTHENTICATION_APIKEY_USERS: 'user-a,user-b'
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    networks:
      - service_network
  page_reader:
    image: semanticsearch-page_reader:latest
    container_name: page_reader
    ports:
      - "8000:8000"
    networks:
      - service_network
  # page_reader:
  #   build:
  #     context: https://github.com/YRL-AIDA/PageR.git#main
  #     dockerfile: ./Dockerfile
  #   container_name: page_reader
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - service_network
  postgres:
    image: postgres:18.0
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - service_network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - service_network

networks:
  service_network: