services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./minio:/data
    command: server /data --console-address ":9001"
    networks:
      - service_network
  qdrant:
    image: qdrant/qdrant:v1.16.1-unprivileged
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    environment:
      QDRANT__SERVICE__API_KEY: "your_secret_api_key_here"
      QDRANT__TELEMETRY_DISABLED: true
      # QDRANT__SERVICE__ENABLE_TLS: "1"
      # QDRANT__TLS__CERT: "/path/to/your/cert.pem"
      # QDRANT__TLS__KEY: "/path/to/your/key.pem"
    volumes:
      - qdrant-storage:/qdrant/storage
    networks:
      - service_network
  page_reader_modified:
    build:
      context: ./PageR
    container_name: page_reader
    ports:
      - "8000:8000"
    networks:
      - service_network
  postgres:
    image: postgres:18.0
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - service_network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - service_network

networks:
  service_network:

volumes:
  qdrant-storage: